### ISSUE TITLE
720 HD or higher moviemaker won't create movies.

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/api#77] opened 2021-06-16 19:32 UTC
![Helioviewer org - Solar and heliospheric image visualization tool 2021-06-21 Same error](https://user-images.githubusercontent.com/35879228/122826992-d33d8200-d2b1-11eb-8dcf-6a22fa94544c.png)
![Helioviewer org - Solar and heliospheric image visualization tool 2021-06-21](https://user-images.githubusercontent.com/35879228/122826994-d3d61880-d2b1-11eb-9102-ece8ec275875.png)
Greetings, I was wondering if you will be able to fix the problem, with your moviemaker. For a year or two, it hasn't been possible to create a movie using the 720 HD or higher option.

**Comment by dgarciabriseno** [comment] 2021-12-30 18:56
Duplicate of #75, Patch is currently live on [beta](https://beta.helioviewer.org)

**Comment by wireeye** [comment] 2021-12-30 23:07
Greetings, I have tried the Beta version of Helioviewer, and it seems to be firing on all cylinders, thus far I have made LASCO C2, and C3 videos from the 720 up to 3840x2160,  4K  and they all process and work as they should. I haven't tried the other filters yet, but I will try them out soon. Thanks for your time and effort.

**Comment by dgarciabriseno** [comment] 2022-01-03 13:51
Thanks for checking that out for me! The patch will be migrated to the main helioviewer site later this month.

**Comment by dgarciabriseno** [comment] 2022-01-20 22:46
Fixed in 3.3.3

**Closed by dgarciabriseno** 2022-01-20 22:46 UTC
Labels: pending-release
