### ISSUE TITLE
No recent SDO-AIA images

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/api#70] opened 2021-10-28 19:12 UTC
Hi
Until about a week ago, the images were usually newer than 30 minutes.
Now images seem to arrive in batches in jhelioviewer, currently the newest AIA-94 is 4 hours, which is a bit long for nowcasting. 
On the helioviewer.org website it is currently 15 minutes.
Would be great if the images in jhelioviewer were similarly recent. 
Many thanks.

**Comment by ebuchlin** [comment] 2021-12-22 10:50
We had an unplanned power outage this night, again we are repairing the database...

**Comment by ebuchlin** [comment] 2021-12-22 13:57
The database is repaired.
Independently from this, we have an issue with movies generation in the web app, we are working on it.

**Comment by dgarciabriseno** [comment] 2021-12-27 20:33
> GSFC beta seems to have no HMI data after December 10th, but AIA is good.
@helioshk This is not still the case, right? There were some issues in the beginning with data ingestion, but all sources should be relatively current. At least within the hour of data becoming available by our data sources.

@ebuchlin If you can reproduce your movie generation issue on helioviewer.org, please let me know.

**Comment by helioshk** [comment] 2021-12-27 20:48
As of now (27/12/21 20:40 UTC):
gsfc-beta: HMI is lagging 4h
gsfc-beta: AIA-94 is lagging 45min
IAS: HMI is lagging 2h30min
IAS: AIA-94 is lagging 35min

For my purpose, HMI is not time critical (6h is ok). For AIA it would be good if it was <<1 hour. Sometimes AIA is delayed up to 3 hours, but currently it is ok.

**Comment by dgarciabriseno** [comment] 2021-12-27 21:19
Ok, I've updated gsfc-beta to try to stay in sync with the LMSAL server. It was set to sync every hour so that would have lead to data being delayed that much longer.

On LMSAL it looks like AIA and HMI data is updated every 15 minutes. and that data itself is probably about 30 minutes old, but that part is out of my control. Hopefully this update helps! :)

**Comment by ebuchlin** [comment] 2021-12-28 10:43
> @ebuchlin If you can reproduce your movie generation issue on helioviewer.org, please let me know.
> Edit: It was this, wasn't it? #64

No, #64 was about the HEK events table. We are still investigating the movie generation issue.

**Comment by dgarciabriseno** [comment] 2021-12-28 14:17
@ebuchlin ok, if you do find a problem then please open a new issue.

@helioshk If beta is working for you, then I will close this issue for now. There is a [separate issue already open](https://github.com/Helioviewer-Project/api/issues/71) for getting production gsfc to serve to JHelioviewer, but it will likely still be some time before I can address it.

**Comment by dgarciabriseno** [comment] 2021-12-28 14:59
Actually I can see that it is still lagging a bit on gsfc-beta. At this moment lmsal has data available for today at UTC Time 14:33, but the latest on beta is UTC 13:53

**Comment by dgarciabriseno** [comment] 2021-12-28 16:15
Ok, I resolved that problem. the downloader.py command I used wasn't doing what I thought it was. Right now AIA is only lagging by 20 minutes, and that's the latest available data we can get. I'll keep an eye on it to see if it will stay up-to-date.

**Comment by dgarciabriseno** [comment] 2022-01-05 17:12
Closing as AIA on beta has stayed up-to-date which I believe resolves @helioshk's issue.

**Comment by helioshk** [comment] 2022-01-28 18:33
There appears to be an issue currently:
SDO/AIA delay on
IAS 1h15m, increasing
GSFC: connection refused
GSFC-beta: not available

**Comment by wafels** [comment] 2022-01-28 19:45
I just tried reaching helioviewer.org from a public network and encountered no problems. There may be some intermittent network connectivity issues at GSFC or elsewhere that are causing an issue. Services at beta.helioviewer.org can go up and down at any moment since we use that site to try new things before they get pushed to the main website.

I'm sorry but I don't have any information about IAS.

**Comment by dgarciabriseno** [comment] 2022-01-28 19:47
The jpip server appears to be running on beta, is shouldn't be experiencing any issues.
It is still not running on GSFC so that explains the connection refused.
I don't have any info on IAS either.

**Comment by helioshk** [comment] 2022-01-28 20:05
Sorry I meant in jhelioviewer, last AIA-94 image is from 16:31 (3h30m ago)

**Comment by bogdanni** [comment] 2022-01-28 20:07
Right now, GSFC beta server returns a response to `getDataSources` which is rejected by JHV. It's related to Hinode. Below the server response.
```
$ wget -q -O - "https://api.beta.helioviewer.org/v2/getDataSources/?verbose=true&enable=[MLSO,TRACE,Hinode,Yohkoh,STEREO_A,STEREO_B,PROBA2]" | jq .
{
  "STEREO_A": {
    "name": "STEREO_A",
    "description": "Solar Terrestrial Relations Observatory Ahead",
    "label": "Observatory",
    "children": {
      "SECCHI": {
        "name": "SECCHI",
        "description": "Sun Earth Connection Coronal and Heliospheric Investigation",
        "label": "Instrument",
        "children": {
          "EUVI": {
            "name": "EUVI",
            "description": "Extreme Ultraviolet Imager",
            "label": "Detector",
            "children": {
              "171": {
                "name": "171 Å",
                "description": "171 Ångström extreme ultraviolet",
                "label": "Measurement",
                "nickname": "EUVI-A 171",
                "sourceId": 20,
                "layeringOrder": 1,
                "start": "2021-12-28 00:07:00",
                "end": "2022-01-25 23:59:15"
              },
              "195": {
                "name": "195 Å",
                "description": "195 Ångström extreme ultraviolet",
                "label": "Measurement",
                "nickname": "EUVI-A 195",
                "sourceId": 21,
                "layeringOrder": 1,
                "start": "2021-12-28 00:05:00",
                "end": "2022-01-25 23:57:30"
              },
              "284": {
                "name": "284 Å",
                "description": "284 Ångström extreme ultraviolet",
                "label": "Measurement",
                "nickname": "EUVI-A 284",
                "sourceId": 22,
                "layeringOrder": 1,
                "start": "2021-12-28 00:13:30",
                "end": "2022-01-25 23:58:30"
              },
              "304": {
                "name": "304 Å",
                "description": "304 Ångström extreme ultraviolet",
                "label": "Measurement",
                "nickname": "EUVI-A 304",
                "sourceId": 23,
                "layeringOrder": 1,
                "start": "2021-12-28 00:05:45",
                "end": "2022-01-25 23:58:15"
              }
            }
          },
          "COR1": {
            "name": "COR1",
            "description": "Coronograph 1",
            "label": "Detector",
            "children": {
              "white-light": {
                "name": "White Light",
                "description": "White Light",
                "label": "Measurement",
                "nickname": "COR1-A",
                "sourceId": 28,
                "layeringOrder": 2,
                "start": "2021-12-28 00:06:00",
                "end": "2022-01-25 23:56:00"
              }
            }
          },
          "COR2": {
            "name": "COR2",
            "description": "Coronograph 2",
            "label": "Detector",
            "children": {
              "white-light": {
                "name": "White Light",
                "description": "White Light",
                "label": "Measurement",
                "nickname": "COR2-A",
                "sourceId": 29,
                "layeringOrder": 3,
                "start": "2021-12-28 00:23:30",
                "end": "2022-01-25 23:53:30"
              }
            }
          }
        }
      }
    }
  },
  "SOHO": {
    "name": "SOHO",
    "description": "Solar and Heliospheric Observatory",
    "label": "Observatory",
    "children": {
      "LASCO": {
        "name": "LASCO",
        "description": "The Large Angle Spectrometric Coronagraph",
        "label": "Instrument",
        "children": {
          "C2": {
            "name": "C2",
            "description": "Coronograph 2",
            "label": "Detector",
            "children": {
              "white-light": {
                "name": "White Light",
                "description": "White Light",
                "label": "Measurement",
                "nickname": "LASCO C2",
                "sourceId": 4,
                "layeringOrder": 2,
                "start": "2021-12-28 00:00:08",
                "end": "2022-01-28 18:00:08"
              }
            }
          },
          "C3": {
            "name": "C3",
            "description": "Coronograph 3",
            "label": "Detector",
            "children": {
              "white-light": {
                "name": "White Light",
                "description": "White Light",
                "label": "Measurement",
                "nickname": "LASCO C3",
                "sourceId": 5,
                "layeringOrder": 3,
                "start": "2021-12-28 00:06:07",
                "end": "2022-01-28 17:54:07"
              }
            }
          }
        }
      }
    }
  },
  "SDO": {
    "name": "SDO",
    "description": "Solar Dynamics Observatory",
    "label": "Observatory",
    "children": {
      "AIA": {
        "name": "AIA",
        "description": "Atmospheric Imaging Assembly",
        "label": "Instrument",
        "children": {
          "94": {
            "name": "94 Å",
            "description": "94 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 94",
            "sourceId": 8,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:23",
            "end": "2022-01-28 19:29:23"
          },
          "131": {
            "name": "131 Å",
            "description": "131 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 131",
            "sourceId": 9,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:19",
            "end": "2022-01-28 19:31:31"
          },
          "171": {
            "name": "171 Å",
            "description": "171 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 171",
            "sourceId": 10,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:09",
            "end": "2022-01-28 19:31:57",
            "default": true
          },
          "193": {
            "name": "193 Å",
            "description": "193 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 193",
            "sourceId": 11,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:29",
            "end": "2022-01-28 19:32:53"
          },
          "211": {
            "name": "211 Å",
            "description": "211 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 211",
            "sourceId": 12,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:22",
            "end": "2022-01-28 19:33:22"
          },
          "304": {
            "name": "304 Å",
            "description": "304 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 304",
            "sourceId": 13,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:05",
            "end": "2022-01-28 19:36:05"
          },
          "335": {
            "name": "335 Å",
            "description": "335 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 335",
            "sourceId": 14,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:01",
            "end": "2022-01-28 19:36:25"
          },
          "1600": {
            "name": "1600 Å",
            "description": "1600 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 1600",
            "sourceId": 15,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:14",
            "end": "2022-01-28 19:33:26"
          },
          "1700": {
            "name": "1700 Å",
            "description": "1700 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 1700",
            "sourceId": 16,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:53",
            "end": "2022-01-28 19:37:41"
          },
          "4500": {
            "name": "4500 Å",
            "description": "4500 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "AIA 4500",
            "sourceId": 17,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:06",
            "end": "2022-01-28 19:00:06"
          }
        },
        "default": true
      },
      "HMI": {
        "name": "HMI",
        "description": "Helioseismic and Magnetic Imager",
        "label": "Instrument",
        "children": {
          "continuum": {
            "name": "Continuum",
            "description": "Intensitygram",
            "label": "Measurement",
            "nickname": "HMI Int",
            "sourceId": 18,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:22",
            "end": "2022-01-28 15:49:08"
          },
          "magnetogram": {
            "name": "Magnetogram",
            "description": "Magnetogram",
            "label": "Measurement",
            "nickname": "HMI Mag",
            "sourceId": 19,
            "layeringOrder": 1,
            "start": "2021-12-28 00:00:22",
            "end": "2022-01-28 15:49:53"
          }
        }
      }
    },
    "default": true
  },
  "PROBA2": {
    "name": "PROBA2",
    "description": "Project for OnBoard Autonomy 2",
    "label": "Observatory",
    "children": {
      "SWAP": {
        "name": "SWAP",
        "description": "Sun watcher using APS detectors and image processing",
        "label": "Instrument",
        "children": {
          "174": {
            "name": "174 Å",
            "description": "174 Ångström extreme ultraviolet",
            "label": "Measurement",
            "nickname": "SWAP 174",
            "sourceId": 32,
            "layeringOrder": 1,
            "start": "2021-12-28 00:18:07",
            "end": "2022-01-28 18:03:40"
          }
        }
      }
    }
  },
  "MLSO": {
    "name": "MLSO",
    "description": "MLSO",
    "label": "Observatory",
    "children": {
      "COSMO": {
        "name": "COSMO",
        "description": "COSMO",
        "label": "Instrument",
        "children": {
          "KCor": {
            "name": "KCor",
            "description": "KCor",
            "label": "Detector",
            "children": {
              "735": {
                "name": "735 NM",
                "description": "735",
                "label": "Measurement",
                "nickname": "COSMO KCor",
                "sourceId": 83,
                "layeringOrder": 1,
                "start": "2022-01-01 18:03:48",
                "end": "2022-01-27 02:16:52"
              }
            }
          }
        }
      }
    }
  },
  "Hinode": {
    "name": "Hinode",
    "description": "",
    "label": "Observatory",
    "children": {
      "XRT": {
        "name": "XRT",
        "description": "",
        "label": "Instrument",
        "children": {
          "Al_med": {
            "name": "Al_med",
            "description": "",
            "label": "Filter Wheel 1",
            "children": {
              "Open": {
                "name": "Open",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Al_med/Open",
                "sourceId": 42,
                "layeringOrder": 1,
                "start": null,
                "end": null
              }
            }
          },
          "Al_poly": {
            "name": "Al_poly",
            "description": "",
            "label": "Filter Wheel 1",
            "children": {
              "Open": {
                "name": "Open",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Al_poly/Open",
                "sourceId": 48,
                "layeringOrder": 1,
                "start": null,
                "end": null
              },
              "Ti_poly": {
                "name": "Ti_poly",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Al_poly/Ti_poly",
                "sourceId": 49,
                "layeringOrder": 1,
                "start": null,
                "end": null
              }
            }
          },
          "Be_med": {
            "name": "Be_med",
            "description": "",
            "label": "Filter Wheel 1",
            "children": {
              "Open": {
                "name": "Open",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Be_med/Open",
                "sourceId": 54,
                "layeringOrder": 1,
                "start": null,
                "end": null
              }
            }
          },
          "Be_thin": {
            "name": "Be_thin",
            "description": "",
            "label": "Filter Wheel 1",
            "children": {
              "Open": {
                "name": "Open",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Be_thin/Open",
                "sourceId": 60,
                "layeringOrder": 1,
                "start": null,
                "end": null
              }
            }
          },
          "Open": {
            "name": "Open",
            "description": "",
            "label": "Filter Wheel 1",
            "children": {
              "Al_mesh": {
                "name": "Al_mesh",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Open/Al_mesh",
                "sourceId": 69,
                "layeringOrder": 1,
                "start": null,
                "end": null
              },
              "Al_thick": {
                "name": "Al_thick",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Open/Al_thick",
                "sourceId": 70,
                "layeringOrder": 1,
                "start": null,
                "end": null
              },
              "Be_thick": {
                "name": "Be_thick",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Open/Be_thick",
                "sourceId": 71,
                "layeringOrder": 1,
                "start": null,
                "end": null
              },
              "Gband": {
                "name": "Gband",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Open/Gband",
                "sourceId": 72,
                "layeringOrder": 1,
                "start": null,
                "end": null
              },
              "Ti_poly": {
                "name": "Ti_poly",
                "description": "",
                "label": "Filter Wheel 2",
                "nickname": "XRT Open/Ti_poly",
                "sourceId": 74,
                "layeringOrder": 1,
                "start": null,
                "end": null
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by bogdanni** [comment] 2022-01-28 20:09
Since I cannot attach JSON, here is the JSON schema against which JHV tries to validate the server response.
```
{
    "$schema" : "http://json-schema.org/draft-06/schema#",
    "title" : "DataSources",
    "description" : "Helioviewer DataSources API response",
    "type" : "object",
    "patternProperties" : {
        "^.*$" : {
            "oneOf" : [
                { "$ref" : "#/definitions/tree_node" },
                { "$ref" : "#/definitions/tree_leaf" }
            ]
        }
    },
    "definitions" : {
        "root_part" : {
            "patternProperties" : {
                "^.*$" : {
                    "oneOf" : [
                        { "$ref" : "#/definitions/tree_node" },
                        { "$ref" : "#/definitions/tree_leaf" }
                    ]
                }
            }
        },
        "tree_node" : {
            "properties" : {
                "name" : { "type" : "string" },
                "description" : { "type" : "string" },
                "children" : { "$ref" : "#/definitions/root_part" },
                "default" : { "type" : "boolean" }
            },
            "required" : [ "name", "description", "children" ]
        },
        "tree_leaf" : {
            "properties" : {
                "name" : { "type" : "string" },
                "description" : { "type" : "string" },
                "sourceId" : {
                    "type" : "integer",
                    "minimum" : 0
                },
                "start" : {
                    "type" : "string",
                    "format" : "sql-date-time"
                },
                "end" : {
                    "type" : "string",
                    "format" : "sql-date-time"
                },
                "default" : { "type" : "boolean" }
            },
            "required" : [ "name", "description", "sourceId", "start", "end" ]
        }
    }
}
```

**Comment by bogdanni** [comment] 2022-01-28 20:11
I see now `children` at 3-depth, I think.

**Comment by bogdanni** [comment] 2022-01-28 20:19
Although the trace of the JSON validator is something like

```
#/Hinode: #: 0 subschemas matched instead of one
#/Hinode/children/XRT: #: 0 subschemas matched instead of one
#/Hinode: required key [sourceId] not found
```

I believe the real issue is that the `start` and `end` are null for those Hinode datasets (there are not files in this server database).

**Comment by bogdanni** [comment] 2022-01-29 00:52
As suspected, the null start and end of Hinode datasets were preventing the user to access the GSFC beta server.

I modified JHV to not reject the entire `getDataSources` server response if that is the case, as it is useful also for a new server installations, where not all data has been ingested.

@helioshk : could you please try again with the build from http://swhv.oma.be/download_test/, you should be able to see the GSFC beta server.

**Closed by bogdanni** 2022-01-29 00:52 UTC

**Comment by helioshk** [comment] 2022-01-29 09:15
@bogdanni Yes it works with 4.3.2, thank you very much.

**Comment by helioshk** [comment] 2022-02-06 12:55
gsfc-beta SDO/AIA and HMI did not update since 4. Feb., SOHO is ok.

Please let me know whether I should report such problems or not. (Or perhaps in a new Issue).
It's not a problem for me as long as at least one server is good.

**Comment by dgarciabriseno** [comment] 2022-02-07 16:06
Yes, please continue to report these issues as you see them. And yes, a new issue would be better. :)

Looking into it now, thanks
