### ISSUE TITLE
Server/data unavailable

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/api#101] opened 2022-02-12 09:13 UTC
Hi,
The IAS server is currently not accessible in JHelioviewer 4.3.2
GSFC-beta is limited available, currently only one AIA frame every 10 minutes (at least for the last few hours)

**Comment by dgarciabriseno** [comment] 2022-03-11 15:52
On GSFC side, GSFC Beta is running well.
GSFC we tried to bring up, and it ran for a couple days, but then it crashed, I'm not sure if it was due to a bug or external factors. Our logfile was filled with this and it caused the hard drive to run out of space which brought down the jpip server. So we've been wary about turning enabling this without a way to prevent this from happening.
![image](https://user-images.githubusercontent.com/94071409/157901404-bb6b2336-08cd-40cb-babb-68e80f0d2d29.png)

**Comment by bogdanni** [comment] 2022-03-11 16:08
I committed https://github.com/Helioviewer-Project/esajpip-SWHV/commit/0c8965eb2793dda22c5c0999547c09fbe23caa98 to log the reason for this failure.
At least we can possibly get some hints. Please clean the logs and re-enable it again.

It's a bit weird that this is happening only at GSFC, didn't hear from IAS of something similar.

**Comment by ebuchlin** [comment] 2022-03-11 19:22
https://helioviewer.ias.u-psud.fr/ uses the same API and works, so we don't understand the JHV issue with the IAS server yet...

**Comment by bogdanni** [comment] 2022-03-11 19:47
```
$ wget "https://helioviewer-api.ias.u-psud.fr/v2/getDataSources/?verbose=true&enable=[MLSO,TRACE,Hinode,Yohkoh,STEREO_A,STEREO_B,PROBA2]"
--2022-03-11 20:45:49--  https://helioviewer-api.ias.u-psud.fr/v2/getDataSources/?verbose=true&enable=[MLSO,TRACE,Hinode,Yohkoh,STEREO_A,STEREO_B,PROBA2]
Resolving helioviewer-api.ias.u-psud.fr (helioviewer-api.ias.u-psud.fr)... 129.175.68.24
Connecting to helioviewer-api.ias.u-psud.fr (helioviewer-api.ias.u-psud.fr)|129.175.68.24|:443... connected.
ERROR: cannot verify helioviewer-api.ias.u-psud.fr's certificate, issued by ‘CN=GEANT OV RSA CA 4,O=GEANT Vereniging,C=NL’:
  Unable to locally verify the issuer's authority.
To connect to helioviewer-api.ias.u-psud.fr insecurely, use `--no-check-certificate'.
```

Something wrong with SSL certificate?

**Comment by bogdanni** [comment] 2022-03-11 19:52
My browser works though, but wget and Java not. Is it a new certificate?

**Comment by bogdanni** [comment] 2022-03-11 19:56
Brand new: "Not Valid Before: Thursday, 10 March 2022 at 01:00:00 Central European Standard Time"
Possibly a new issuer not propagated yet?

**Comment by ebuchlin** [comment] 2022-03-11 20:46
Stéphane solved the issue: "chain certificate was incomplete in server configuration, which most browsers ignore, but which created the problem with JHV". As far as I understand there was also another minor issue with the TLS version used by Apache.

**Comment by bogdanni** [comment] 2022-03-14 14:45
The certificate problem was fixed. Now there is another problem.

**Comment by farm24** [comment] 2022-03-14 17:15
> The certificate problem was fixed. Now there is another problem.

Hopefully it gets fixed soon so I can analyze the images from last nights M class flare

**Comment by farm24** [comment] 2022-03-14 18:20
there are none on jhelioviewer 
<img width="86" alt="Screen Shot 2022-03-14 at 1 19 52 PM" src="https://user-images.githubusercontent.com/77849362/158236039-958267d5-3596-4b0d-98ee-16011ff89555.png">

**Comment by helioshk** [comment] 2022-03-14 18:29
Do you have the latest jhelioviewer version?

**Comment by bogdanni** [comment] 2022-03-14 19:07
Please get the beta from http://swhv.oma.be/download_test/

**Comment by ebuchlin** [comment] 2022-03-15 10:42
We confirm that there was a socket timeout when requesting a JPIP URL. The server load was very high because of Apache, and we had to reboot, but now we again have to repair the database following the reboot...

**Comment by bogdanni** [comment] 2022-03-16 16:12
@ebuchlin IAS is up and working

@dgarciabriseno I committed a change to the esajpip server to use a rolling file appender for logging, limited in size to 1GB. The log needs to be supervised for those log storms which made it to grow uncontrollably in order to identify the cause. Please re-enable JPIP.

**Comment by dgarciabriseno** [comment] 2022-03-16 17:44
Thanks @bogdanni, I'll get it set up.

**Comment by helioshk** [comment] 2022-04-07 18:22
I'll close this for now as the IAS server seems to be running stable.
GSFC-beta still has sporadic gaps, but that is covered in another issue https://github.com/Helioviewer-Project/api/issues/97

**Comment by helioshk** [comment] 2022-04-18 11:33
IAS server offline again (and helioviewer.org with it)

**Comment by ebuchlin** [comment] 2022-04-18 12:59
Whole IAS is offline, there seems to be a University network issue.

**Comment by dgarciabriseno** [comment] 2022-04-18 13:36
helioviewer.org is available now.

**Comment by ebuchlin** [comment] 2022-04-18 20:11
IAS back online, with some data to catch up.

**Comment by helioshk** [comment] 2022-04-21 09:20
GSFC beta is offline.

**Comment by dgarciabriseno** [comment] 2022-04-21 13:05
Thanks, it's back.

**Comment by dgarciabriseno** [comment] 2022-04-22 13:36
Working on it. The part that's supposed to stay updated keeps crashing for some reason. Working fine for other data sources, and working fine on main GSFC 🤦🏼‍♂️

**Comment by dgarciabriseno** [comment] 2022-04-22 16:53
Found the error, it's catching up now.

**Comment by helioshk** [comment] 2022-04-22 22:01
Thank you!

**Comment by helioshk** [comment] 2022-05-28 21:47
Currently no new SDO/AIA images in JHV since 17:22 and on helioviewer.org since ~17:01 (depending on wavelength)

**Comment by helioshk** [comment] 2022-05-30 19:00
Can anybody have a look? No SDO images since Saturday. 
Thanks

**Comment by wafels** [comment] 2022-05-30 19:07
We are aware of the issue and are looking in to it.

**Comment by dgarciabriseno** [comment] 2022-05-31 13:57
Sorry, disaster struck over the holiday weekend! Images are being restored now.

**Comment by helioshk** [comment] 2022-06-30 22:21
SDO/AIA-171 images seem to be missing, probably since the Stanford power outage.
21-Jun 21:00 to 27-Jun 21:00
28-Jun 23:05 to now

**Comment by dgarciabriseno** [comment] 2022-07-01 12:09
The scripts are running to fill this in. Most of 21-Jun to 21-Jun is filled in, once that completes it'll catch up to 28-Jun to now.

**Comment by helioshk** [comment] 2022-10-18 14:08
SDO/HMI is unavailable since Oct/13

**Comment by ebuchlin** [comment] 2022-10-21 10:32
There seems to have been some hiccup in the original files production. Now that they are produced again, both GSFC and MEDOC/IAS have HMI files from this morning (5 hours delay).

**Comment by dgarciabriseno** [comment] 2022-10-21 13:17
Yep, this time it's not our fault! It's an upstream problem. I heard some fiber line was cut (I don't actually know where) and so the jp2 files weren't being generated for a while for us to pick up. They did some workaround to be able to process a subset of the data, though.

Last update I got was that they should start backfilling this weekend or next week. Then when the data is available we will also backfill. Should go back to normal operation after that.

**Comment by helioshk** [comment] 2022-10-21 13:22
Great, thank you!

**Comment by helioshk** [comment] 2022-10-27 00:20
There seem to be an issue with GSFC-beta:
SDO/AIA is unavailable since Oct/18
SDO/HMI unavailable since Oct/13

IAS is good.

**Comment by dgarciabriseno** [comment] 2022-10-27 11:49
Thanks for the report, beta was being sneaky about being behind. Backfilling now.

**Comment by helioshk** [comment] 2022-11-28 23:26
SDO/AIA and HMI are unavailable since late Nov 26.

**Comment by ebuchlin** [comment] 2022-11-29 08:13
GSFC has caught up, IAS too for HMI, still catching up for AIA.

**Comment by dgarciabriseno** [comment] 2022-12-16 16:59
STEREO-A is behind at GSFC.
@wafels Can you take a look?

**Comment by helioshk** [comment] 2023-01-02 11:54
I'm not sure if that's an issue, but GSFC-beta doesn't have old (3./4. October 2022) HMI data, IAS is good though.

> Error encountered during JPX creation: Error creating JPX file
> COMMAND:
> PATH="" /usr/local/bin/kdu_merge -s /dev/stdin
> _[error message truncated by me]_
> Error in Kakadu File Format Support:
> Unable to open input file,
> "/mnt/data/jp2/HMI/2022/10/03/continuum/2022_10_03__00_00_30_900__SDO_HMI_HMI_c
> ontinuum.jp2".

**Comment by dgarciabriseno** [comment] 2023-01-03 12:49
The beta server only holds data for the last 90 days so this is somewhat expected. But really it should have said data wasn't available for that date rather than trying to access a non-existent file...

**Comment by dgarciabriseno** [comment] 2023-01-03 18:50
If anything like this comes up again, please open a separate api issue. That way we can track more specific instances of data being unavailable.

**Closed by dgarciabriseno** 2023-01-03 18:50 UTC
