### ISSUE TITLE
[Feature Request] Access SP Level 2 Data from HAO

### ISSUE THREAD

**Issue by Cubostar** [Helioviewer-Project/api#47] opened 2019-08-06 00:45 UTC
At the moment only level 0 data can be downloaded, which is uncalibrated and hard to use. It would be nice to get level 2 data, which is already inverted and ready for data analysis.

**Comment by wafels** [comment] 2021-12-21 17:17
Helioviewer does not provide any SP data at all. Closing this issue - maybe it was intended for SunPy?

**Closed** 2021-12-21 17:17 UTC
