### ISSUE TITLE
XRT backfill processes?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#254] opened 2023-02-14 15:57 UTC
A user has noticed that XRT data isn’t showing up consistently in Helioviewer. The user noted that on 2022/08/30 at 16:42 when they know that there is XRT Al-poly data nothing is showing up in Helioviewer until 2022/08/31 at 10:12:29 UT.

Are XRT backfill processes running to look for missing data?

**Comment by wafels** [comment] 2023-02-15 14:59
Looks like there are data available on the at the XRT website.

**Comment by dgarciabriseno** [comment] 2023-02-21 15:12
Looking into this now.

**Comment by wafels** [comment] 2023-02-21 16:07
Ah that’s more serious. Can you send me the error?

**Comment by dgarciabriseno** [comment] 2023-02-21 16:25
There isn't much in the logs. We should probably have downloader.py log more detailed info.
```
xrt-backfill.log:3578:2022-12-05 03:04:00 [ERROR] kdu_transcode: /data/hvpull/incoming/2022_11_15__23_49_24_987__HINODE_XRT.jp2
xrt-backfill.log:3579:2022-12-05 03:04:00 [ERROR] Quitting due to kdu_transcode error
```

**Comment by dgarciabriseno** [comment] 2023-02-21 16:25
manually backfilling that time range didn't seem to cause any issues though.

**Comment by dgarciabriseno** [comment] 2023-02-21 17:46
I did some analysis on the logs, most of the files that failed kdu transcode seem to still have made it into image archive at some point. So the issue isn't as big as it seemed. out of a little over 67,000 transcode errors in the logs, 349 of those images aren't in the archive.

These errors happen pretty regularly. Not on a lot of images (I counted 9 on Feb 1st, only  2 on Feb 17, 15 on Feb 18), but regularly enough I think it's worth looking closer at.

**Comment by dgarciabriseno** [comment] 2023-02-21 18:33
I started processes to attempt to backfill the XRT and SWAP images that had errors.

There are several SOHO and STEREO images that had failures that I can't backfill. They might have to be regenerated.

**Comment by dgarciabriseno** [comment] 2023-02-21 19:03
I have #260 running. I'm going to wait to merge until I catch an error and make sure there's no issues with the patch.
This will tell us why the kdu_transcode errors are happening and let me debug further.

**Comment by dgarciabriseno** [comment] 2023-02-23 16:47
I don't see any new errors between yesterday and today, so this is looking good. Closing.

**Closed by dgarciabriseno** 2023-02-23 16:47 UTC
